/**
 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */

const sidebars = {
  // defaultSidebar : [
  //   'api/authentication',
  //   'api/error-handling',
  //   'api/file-schemas',
  //   'api/rate-limits',
  //   'api/webhooks',
  //   {
  //     type : 'category',
  //     label : 'Customer APIs',
  //     items : ['api/customer-apis/index'],
  //   },
  // ],

  docSidebar: [{ type: "autogenerated", dirName: "." }],

  // esEngageSidebar : [
  //   'es-engage/index',
  //   {
  //     type : 'category',
  //     label : 'User Guide',
  //     items : ['es-loyalty/user-guide/index']
  //   },
  //   {
  //     type : 'category',
  //     label : 'Feature Sheet',
  //     items : ['es-loyalty/feature-sheet/index']
  //   },
  //   {
  //     type : 'category',
  //     label : 'Tutorials',
  //     items : ['es-loyalty/tutorials/index']
  //   },
  //   // {
  //   //   type : 'category',
  //   //   label : 'API Reference',
  //   //   items : ['es-loyalty/api-reference/index']
  //   // },
  // ],

  // esLoyaltySidebar : [
  //   'es-loyalty/index',
  //   {
  //     type : 'category',
  //     label : 'User Guide',
  //     items : ['es-loyalty/user-guide/index']
  //   },
  //   {
  //     type : 'category',
  //     label : 'Feature Sheet',
  //     items : ['es-loyalty/feature-sheet/index']
  //   },
  //   {
  //     type : 'category',
  //     label : 'Tutorials',
  //     items : ['es-loyalty/tutorials/index']
  //   },
  //   {
  //     type : 'category',
  //     label : 'Release Notes',
  //     items : [
  //       'es-loyalty/release-notes/index',
  //       'es-loyalty/release-notes/2026/4.7.1',
  //       'es-loyalty/release-notes/2025/4.6.0',
  //     ]
  //   },

  // ],

  // esLoyaltyBoostSidebar : [
  //   'es-loyalty-boost/index',
  //   {
  //     type : 'category',
  //     label : 'User Guide',
  //     items : ['es-loyalty/user-guide/index']
  //   },
  //   {
  //     type : 'category',
  //     label : 'Feature Sheet',
  //     items : ['es-loyalty/feature-sheet/index']
  //   },
  //   {
  //     type : 'category',
  //     label : 'Tutorials',
  //     items : ['es-loyalty/tutorials/index']
  //   },
  //   // {
  //   //   type : 'category',
  //   //   label : 'API Reference',
  //   //   items : ['es-loyalty/api-reference/index']
  //   // },
  // ],

  // apiReferenceSidebar : [
  //   {
  //     type: 'category',
  //     label: 'API Reference',
  //     link: { type: 'doc', id: 'api-reference/index' }, // the api reference landing page
  //     items: [{ type: 'autogenerated', dirName: 'api-reference' }],
  //   },
  // ]
};

export default sidebars;
